---
blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/NHAS/webauthn
    about: Read the documentation
  - name: Question/Other
<<<<<<< HEAD
    url: https://github.com/NHAS/webauthn/discussions/new
    about: Discuss other questsions etc.
=======
    url: https://github.com/go-webauthn/webauthn/discussions/new
    about: Discuss other questions etc.
>>>>>>> upstream/master
...
